language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install xvfb curl wget
  - sudo curl -o wkhtmltox-0.12.1_linux-precise-amd64.deb 'http://softlayer-ams.dl.sourceforge.net/project/wkhtmltopdf/archive/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb'
  - sudo dpkg -i ./wkhtmltox-0.12.1_linux-precise-amd64.deb
  - composer install
